In [1]:
import sys
sys.path.append('..')
from theano import function, config, shared, sandbox
import theano.tensor as T
import numpy as np
import theano_lstm


Using gpu device 0: GeForce GTX TITAN X


In [2]:
config.mode="FAST_COMPILE"
hidden_size = 128
network = theano_lstm.lstm_rnn(300,
                  [(hidden_size, hidden_size)],
                  150, dropout=0.2)
# network.initialize_training_adadelta()
network.initialize_training_adam(alpha=5e-5, beta1=0.9)

In [70]:
network.initialize_network_weights()
for p in network.list_all_params():
    p.set_value(p.get_value()*0.7)

In [67]:
old_grad_calc = old_grad_fun(vectors, lengths, answers)/1.000000001
old_grad_calc

array([[  7.69233152e+12,   9.01659073e+12,   1.26909636e+13, ...,
         -3.74160543e+12,  -3.12036945e+13,  -1.25824726e+13],
       [ -2.68804974e+13,  -1.82994883e+13,  -4.45719123e+13, ...,
         -5.45421210e+12,   6.99111938e+12,   1.66316933e+12],
       [  1.23057314e+12,  -1.42208978e+12,  -1.30754229e+12, ...,
         -1.71519194e+13,  -1.04429296e+12,  -2.24670641e+13],
       ..., 
       [  4.61777351e+13,  -5.84718798e+12,   5.75633663e+13, ...,
          1.90069562e+13,  -1.15899997e+13,  -1.12533743e+13],
       [  1.27108037e+13,   3.18294783e+13,   1.03213401e+13, ...,
          1.01879529e+13,  -7.86915813e+12,  -1.81620577e+13],
       [ -1.16482764e+13,   2.67857900e+13,   4.78646056e+12, ...,
          2.13522642e+13,   7.35598713e+13,   1.94090033e+13]], dtype=float32)

In [35]:
grad_obj = network.adam_grads[0]

In [51]:
old_grad_obj = grad_obj*1.000000001

In [46]:
curr_norm = grad_obj.norm(2, axis=1)
# curr_norm = T.addbroadcast(curr_norm, 0)
curr_norm = curr_norm.dimshuffle([0, 'x'])
scale_fac = network.adam_hyperparam_list[0]/curr_norm
print curr_norm.broadcastable
new_grad = grad_obj*scale_fac

(False, True)


In [49]:
norm_fun = function(network._lstm_rnn__inp_list, curr_norm)

In [39]:
scale_fac_fun = function(network._lstm_rnn__inp_list, scale_fac)

In [52]:
old_grad_fun = function(network._lstm_rnn__inp_list, old_grad_obj)

In [22]:
grad_fun = function(network._lstm_rnn__inp_list, new_grad)

In [50]:
curr_norm_calc = norm_fun(vectors, lengths, answers)
curr_norm_calc

array([[ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ inf],
       [ i

In [71]:
scale_fac_calc = scale_fac_fun(vectors, lengths, answers)
scale_fac_calc

array([[  1.76298371e-07],
       [  6.56361294e-08],
       [  7.90249644e-08],
       [  1.13884608e-08],
       [  3.80782446e-08],
       [  1.48492205e-08],
       [  5.73712704e-08],
       [  1.61984204e-08],
       [  3.70072257e-08],
       [  3.20477760e-08],
       [  6.37140687e-08],
       [  4.81401621e-08],
       [  1.33169662e-08],
       [  1.22192546e-07],
       [  3.75578182e-08],
       [  1.24300300e-07],
       [  8.83644091e-08],
       [  2.37180533e-08],
       [  1.16589320e-07],
       [  3.97376994e-08],
       [  2.43791277e-07],
       [  9.59257989e-08],
       [  3.08135455e-08],
       [  3.14240189e-08],
       [  9.67313269e-08],
       [  7.28094705e-08],
       [  6.33974082e-08],
       [  1.78709357e-07],
       [  8.37233500e-08],
       [  4.25970335e-08],
       [  3.74816338e-08],
       [  5.98162870e-08],
       [  2.78558243e-08],
       [  4.79055231e-08],
       [  9.65346771e-08],
       [  4.83751563e-08],
       [  1.46026560e-08],
 

In [69]:
new_grad_calc = grad_fun(vectors, lengths, answers)
new_grad_calc

array([[ 0.07412253,  0.08688296,  0.12228884, ..., -0.03605373,
        -0.30067563, -0.12124343],
       [-0.22462016, -0.15291511, -0.37245405, ..., -0.04557676,
         0.05841954,  0.01389786],
       [ 0.00902044, -0.01042431, -0.00958464, ..., -0.12572826,
        -0.00765495, -0.16468973],
       ..., 
       [ 0.29069477, -0.0368088 ,  0.36236879, ...,  0.11965124,
        -0.07296054, -0.07084144],
       [ 0.06705038,  0.16790274,  0.0544458 , ...,  0.05374217,
        -0.04151036, -0.09580614],
       [-0.06037867,  0.13884376,  0.02481055, ...,  0.11067915,
         0.38129652,  0.10060629]], dtype=float32)

In [ ]:
o

In [ ]:
grad = network.adam_grads[0]

In [ ]:
grad_fun = function(network._lstm_rnn__inp_list, grad)

In [17]:
import data_managers
data_butler = data_managers.character_data_manager('/home/arimorcos/Github/CS281-Final-Project/data manager/')
data_butler.set_batch_size(5)
vectors, lengths, answers = data_butler.offer_data()

Batch Size = 5;  Stride = 5


In [ ]:
network.adam_hyperparam_list

In [ ]:
curr_norm

In [ ]:
curr_norm = x.norm(2, axis=1)
scale_fac = network.adam_hyperparam_list[0]/curr_norm

In [ ]:
scale_fac.T.

In [ ]:
scale_fac.broadcastable

In [ ]:
dir(x)

In [ ]:
help(x.T.clip)

In [ ]:
help(x.norm)

In [ ]:
help(x.T.norm)

In [ ]:
x = shared(np.array([1, 2, 3, 4]).astype(config.floatX))

In [ ]:
x.get_value()[0].dtype

In [ ]:
network.adam_hyperparam_list.get_value()[0]

In [ ]:
y = np.ones(shape=(5,10))

In [ ]:
np.mean(y, axis=1)